resources:
  containers:
  - container: my_container
    image: openjdk:latest

pool:
  vmImage: 'ubuntu-16.04'

container: my_container

steps:
- script: ./gradlew build -x test
  displayName: 'Gradle Build'

- script: ./gradlew test
  displayName: 'Gradle Test'
